### ISSUE TITLE
Run commands from the nearest package.json's directory

### ISSUE THREAD

**Issue by kevinwolfcr** [usmanyunusov/nano-staged#40]
### Clear and concise description of the problem

Sometimes, running `eslint` on a monorepo workspace causes errors because the `eslint` binary is being run from the root workspace, causing issues for instance when using the TypeScript plugin, which relies on the `tsconfig.json` being on the workspace directory.

### Suggested solution

When executing any of the scripts specified in `nano-staged`, we could use [`find-up`](https://www.npmjs.com/package/find-up) to determine where the nearest `package.json` is located and use its directory as the `cwd`.

**Comment by andrey-skl** [comment]
Hi!

In our monorepository, we face issue that `ESLint`, ran by `nano-staged`, ignores `.eslintignore` files in subpackages. I suppose this may be relevant.

@kevinwolfcr I can see that this request is closed as "completed", but we don't see any commits or fixes in codebase.

Could you please tell, if this request was addressed, or is it closed as irrelevant?
